Update auto-unit-testing.yml

diff --git a/.github/workflows/auto-unit-testing.yml b/.github/workflows/auto-unit-testing.yml
--- a/.github/workflows/auto-unit-testing.yml
+++ b/.github/workflows/auto-unit-testing.yml
@@ -1,46 +1,46 @@
-# This workflow will build a .NET project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
+# # This workflow will build a .NET project
+# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
 
-name: Atomation_Testing_on_Push_Pull_Request
+# name: Atomation_Testing_on_Push_Pull_Request
 
-on:
-  push:
-    branches: [ "dev", "main" ]    
-  pull_request:
-    branches: [ "dev", "main" ]
-    #Manual workflow start
-  workflow_dispatch:
+# on:
+#   push:
+#     branches: [ "dev", "main" ]    
+#   pull_request:
+#     branches: [ "dev", "main" ]
+#     #Manual workflow start
+#   workflow_dispatch:
   
-permissions: 
-  checks: write
+# permissions: 
+#   checks: write
   
-jobs:
+# jobs:
   
-  build-and-test:
+#   build-and-test:
 
-    runs-on: windows-2022
-    env:
-      SOLUTION_PATH: 'Streetcode\Streetcode.sln'
-      BUILD_CONFIG: 'Debug'
+#     runs-on: windows-2022
+#     env:
+#       SOLUTION_PATH: 'Streetcode\Streetcode.sln'
+#       BUILD_CONFIG: 'Debug'
             
-    steps:
-    - uses: actions/checkout@v4
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v4
-      with:
-        dotnet-version: 6.0.x
-    - name: Restore dependencies
-      run: dotnet restore $env:SOLUTION_PATH
-    - name: Build
-      run: dotnet build $env:SOLUTION_PATH --configuration $env:BUILD_CONFIG --no-restore
-    - name: Test
-      run: dotnet test $env:SOLUTION_PATH --configuration $env:BUILD_CONFIG --no-build --verbosity normal --logger "trx;LogFileName=test-res.trx" || true
-    - name: Create-Testing-Result-Report
-      uses: phoenix-actions/test-reporting@v8      
-      if: success() || failure()
-      id: test-report
-      with:
-        name: Test-Results
-        reporter: dotnet-trx
-        path: "**/test-res.trx"        
-        fail-on-error: true
+#     steps:
+#     - uses: actions/checkout@v4
+#     - name: Setup .NET
+#       uses: actions/setup-dotnet@v4
+#       with:
+#         dotnet-version: 6.0.x
+#     - name: Restore dependencies
+#       run: dotnet restore $env:SOLUTION_PATH
+#     - name: Build
+#       run: dotnet build $env:SOLUTION_PATH --configuration $env:BUILD_CONFIG --no-restore
+#     - name: Test
+#       run: dotnet test $env:SOLUTION_PATH --configuration $env:BUILD_CONFIG --no-build --verbosity normal --logger "trx;LogFileName=test-res.trx" || true
+#     - name: Create-Testing-Result-Report
+#       uses: phoenix-actions/test-reporting@v8      
+#       if: success() || failure()
+#       id: test-report
+#       with:
+#         name: Test-Results
+#         reporter: dotnet-trx
+#         path: "**/test-res.trx"        
+#         fail-on-error: true
